import type { CoachMarkTour } from '../types';

/** The pages behind the avatar. */
export const ACCOUNT_TOURS: CoachMarkTour[] = [
  {
    id: 'notifications',
    area: 'Your account',
    version: 1,
    title: 'Notifications',
    description: 'What lands here, and how to choose what does.',
    startPath: '/notifications',
    autoStart: true,
    requires: ['notifications-preferences-link'],
    audience: 'everyone',
    steps: [
      {
        id: 'what',
        title: 'What your agents did',
        body: 'A run that finished or failed, a ticket filed, a message sent, a chat or agent shared with you: the things that changed something, not every step along the way. Each card links to what it is about.',
      },
      {
        id: 'choose',
        title: 'Choose what appears',
        target: 'notifications-preferences-link',
        placement: 'bottom',
        body: 'Which events reach you, and where — here, by email, or in WebEx — is set under Preferences, event by event, with overrides per agent.',
      },
      {
        id: 'mark',
        title: 'Clear the pile',
        target: 'notifications-mark-all',
        placement: 'bottom',
        body: 'Mark everything read at once, or tick a few cards and act on just those. The count on your avatar is the unread ones.',
      },
    ],
  },
  {
    id: 'preferences',
    area: 'Your account',
    version: 1,
    title: 'Preferences',
    description:
      'Appearance, voice, the tools a chat starts with, what it may do, and your notifications.',
    startPath: '/preferences',
    autoStart: true,
    requires: ['prefs-appearance'],
    audience: 'everyone',
    steps: [
      {
        id: 'appearance',
        title: 'How it looks',
        target: 'prefs-appearance',
        placement: 'bottom',
        body: 'Light, dark, or follow the system. Picking one is its own preview; Save makes it follow you to other devices.',
      },
      {
        id: 'voice',
        title: 'How it sounds',
        target: 'prefs-voice',
        placement: 'bottom',
        body: 'When the organization has a voice service: the voice that reads replies, its pace, the language it listens for, and whether voice mode is press-to-talk.',
      },
      {
        id: 'tools',
        title: 'What a new chat starts with',
        target: 'prefs-default-tools',
        placement: 'auto',
        body: 'The connectors a fresh chat may use, and a separate set for code projects. Any chat can still narrow its own.',
      },
      {
        id: 'permissions',
        title: 'What a chat may do without asking',
        target: 'prefs-permissions',
        placement: 'auto',
        body: 'Tools that change something outside the conversation ask first. Answer here once, per tool or per group, and they stop asking — or keep asking, if that is what you want.',
      },
      {
        id: 'notifications',
        title: 'Which events reach you',
        target: 'prefs-notifications',
        placement: 'auto',
        body: 'Event by event: in the app, by email, or in WebEx. Override any of it for a particular agent, and choose where pop-ups appear.',
      },
    ],
  },
  {
    id: 'batch-jobs',
    area: 'Your account',
    version: 1,
    title: 'Batch jobs',
    description: 'Running a pipeline over a folder of files, once or on a schedule.',
    startPath: '/batch-jobs',
    autoStart: true,
    requires: ['batch-jobs-new'],
    audience: 'everyone',
    steps: [
      {
        id: 'new',
        title: 'Start a batch',
        target: 'batch-jobs-new',
        placement: 'bottom',
        body: 'Point a pipeline — document OCR, say — at a folder on one of your file shares and it works through every file, reporting what succeeded and what did not.',
      },
      {
        id: 'schedules',
        title: 'Or make it recurring',
        target: 'batch-jobs-schedules',
        placement: 'bottom',
        body: 'A schedule runs the same batch again on the days you choose, skipping the organization’s holidays.',
      },
      {
        id: 'list',
        title: 'Every run, by status',
        body: 'Batches you have started are listed below, newest first; the tabs narrow them to running, succeeded, partial or failed. Open one for its files.',
      },
    ],
  },
  {
    id: 'tools-usage',
    area: 'Your account',
    version: 1,
    title: 'Tools',
    description: 'Which tools have been called, how often, and by what.',
    startPath: '/usage',
    autoStart: true,
    requires: ['usage-period'],
    audience: 'everyone',
    steps: [
      {
        id: 'period',
        title: 'Pick a window',
        target: 'usage-period',
        placement: 'bottom',
        body: 'Today, this week, this month, or longer. An operator can also widen the view from just you to everyone.',
      },
      {
        id: 'stats',
        title: 'The totals',
        target: 'usage-stats',
        placement: 'bottom',
        body: 'How many tool calls, across how many tools, with the trend below and a breakdown by connector, by agent, and — for an operator — by person.',
      },
    ],
  },
  {
    id: 'my-usage',
    area: 'Your account',
    version: 1,
    title: 'My usage',
    description: 'Your tokens, runs and tool calls over time.',
    startPath: '/utilization',
    autoStart: true,
    requires: ['utilization-period'],
    audience: 'everyone',
    steps: [
      {
        id: 'period',
        title: 'Pick a window',
        target: 'utilization-period',
        placement: 'bottom',
        body: 'The same windows as the Tools page, for what your own chats and agents have used.',
      },
      {
        id: 'stats',
        title: 'What it adds up to',
        target: 'utilization-stats',
        placement: 'bottom',
        body: 'Tokens spent, agent runs, tool calls, and tokens per run — the number to watch when an agent grows expensive.',
      },
    ],
  },
  {
    id: 'activity',
    area: 'Your account',
    version: 1,
    title: 'Activity',
    description: 'The log of what Renkei did on your behalf, and how to search it.',
    startPath: '/logs',
    autoStart: true,
    requires: ['logs-search'],
    audience: 'everyone',
    steps: [
      {
        id: 'levels',
        title: 'By severity',
        target: 'logs-levels',
        placement: 'bottom',
        body: 'Errors only, or everything down to debug detail. The log is what a support conversation starts from.',
      },
      {
        id: 'search',
        title: 'By what happened',
        target: 'logs-search',
        placement: 'bottom',
        body: 'Search by message, level or any recorded attribute; Syntax shows the query language. Each entry can be copied for whoever is helping you.',
      },
    ],
  },
  {
    id: 'about',
    area: 'Your account',
    version: 1,
    title: 'About Renkei',
    description: 'The version you are on, and what has changed.',
    startPath: '/about',
    autoStart: false,
    requires: ['about-changelog'],
    audience: 'everyone',
    steps: [
      {
        id: 'changelog',
        title: 'What has changed',
        target: 'about-changelog',
        placement: 'bottom',
        body: 'Every release that changed something you would notice, newest first. The build and commit at the foot of the page are what to quote when reporting a problem.',
      },
    ],
  },
  {
    id: 'tutorials',
    area: 'Your account',
    version: 1,
    title: 'Tutorials',
    description: 'Replaying a tour, and stopping them from starting on their own.',
    startPath: '/tutorials',
    autoStart: false,
    requires: ['tutorials-switch'],
    audience: 'everyone',
    steps: [
      {
        id: 'switch',
        title: 'Tours on their own, or not',
        target: 'tutorials-switch',
        placement: 'bottom',
        body: 'On, a page’s tour greets you the first time you visit it. Off, tours only run when you start one from this list.',
      },
      {
        id: 'list',
        title: 'Every tour, and where you got to',
        body: 'Each tour shows whether you finished it, skipped it, or have not started; Replay runs it again from the beginning. Operators see the console’s tours here too.',
      },
    ],
  },
];
