import type { CoachMarkTour } from '../types';

/** The chat thread and the pages around it. */
export const CHAT_TOURS: CoachMarkTour[] = [
  {
    id: 'chat',
    area: 'Chat',
    version: 1,
    title: 'Chat',
    description:
      'The composer: what to type, which tools the assistant may use, and the model it runs on.',
    startPath: '/chat/new',
    autoStart: true,
    requires: ['chat-composer'],
    audience: 'everyone',
    steps: [
      {
        id: 'composer',
        title: 'Ask in plain words',
        target: 'chat-composer',
        placement: 'top',
        body: 'Type what you need. Enter sends, Shift+Enter starts a new line, and a slash opens your prompt libraries.',
      },
      {
        id: 'tools',
        title: 'Which tools it may use',
        target: 'chat-tools',
        placement: 'top',
        body: 'The assistant reaches into your connectors through tools. Narrow the set for a chat here; your default set is under Preferences.',
      },
      {
        id: 'model',
        title: 'Pick a model',
        target: 'chat-model',
        placement: 'top',
        body: 'Each chat runs on one model. Switch it here, and turn on extended thinking for a harder question.',
      },
      {
        id: 'send',
        title: 'Send it',
        target: 'chat-send',
        placement: 'top',
        body: 'The reply streams in below. While it is running, Send queues your next message and Stop ends the turn.',
      },
    ],
  },
  {
    id: 'chat-composer-more',
    area: 'Chat',
    version: 1,
    title: 'More in the composer',
    description: 'Attachments, prompts from a library, dictation, and the thread menu.',
    startPath: '/chat/new',
    // Only on request: the chat tour already greets a first thread, and
    // two tours on one page is one too many.
    autoStart: false,
    requires: ['chat-prompt'],
    audience: 'everyone',
    steps: [
      {
        id: 'attach',
        title: 'Attach a file',
        target: 'chat-attach',
        placement: 'top',
        body: 'Drop a file on the box, paste one, or pick one here. It uploads at once and goes with your next message. Attachments need the organization to have storage set up; without it the button is not here.',
      },
      {
        id: 'prompt',
        title: 'Start from a prompt',
        target: 'chat-prompt',
        placement: 'top',
        body: 'Insert a prompt from one of your libraries, or a shared one. Typing a slash into an empty box opens the same picker, which also holds Compact this conversation for a long thread.',
      },
      {
        id: 'voice',
        title: 'Say it instead',
        target: 'chat-voice',
        placement: 'top',
        body: 'When the organization has a voice service, dictate into the box and fix the words before sending, or open the voice conversation for a hands-free exchange.',
      },
      {
        id: 'more',
        title: 'The thread menu',
        target: 'chat-more',
        placement: 'bottom',
        body: 'Rename the chat, archive it, share it read-only with a colleague, or delete it. In a code project the menu also holds the environment and the changes.',
      },
    ],
  },
  {
    id: 'chat-permission',
    area: 'Chat',
    version: 1,
    title: 'When the assistant asks first',
    description: 'The card a chat shows before a tool changes something outside the conversation.',
    startPath: '/chat/new',
    // Starts on its own the first time a card like this appears — that is
    // when the question means something.
    autoStart: true,
    requires: ['chat-permission-card'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Allow this?',
        target: 'chat-permission-card',
        placement: 'bottom',
        body: 'A tool that changes something in a connected system waits for your yes. Allow once for this turn, Always allow to stop being asked for this tool, or Deny. Your standing answers are under Preferences, in What a chat may do.',
      },
    ],
  },
  {
    id: 'projects',
    area: 'Chat',
    version: 1,
    title: 'Projects',
    description:
      'A shared workspace of instructions, files and memory that every chat inside it reads.',
    startPath: '/chat/projects',
    autoStart: true,
    requires: ['projects-new'],
    audience: 'everyone',
    steps: [
      {
        id: 'new',
        title: 'Make a project',
        target: 'projects-new',
        placement: 'bottom',
        body: 'A project holds standing instructions, files and notes, and every chat started inside it reads all three. Share it and your colleagues chat with the same context.',
      },
      {
        id: 'lists',
        title: 'Yours, and shared with you',
        body: 'Projects you made are listed first; ones colleagues shared with you follow. A chat started from a project shows the project name in the menu.',
      },
    ],
  },
  {
    id: 'project',
    area: 'Chat',
    version: 1,
    title: 'Inside a project',
    description: 'What each section of a project does for the chats inside it.',
    startPath: '/chat/projects',
    autoStart: true,
    requires: ['project-about'],
    audience: 'everyone',
    steps: [
      {
        id: 'chats',
        title: 'Its chats',
        target: 'project-chats',
        placement: 'auto',
        body: 'Every chat started here. New chat opens one that already knows the project.',
      },
      {
        id: 'about',
        title: 'Standing instructions',
        target: 'project-about',
        placement: 'auto',
        body: 'The name, a description, and instructions every chat in the project follows: who the assistant is for, what to keep to, what to avoid.',
      },
      {
        id: 'files',
        title: 'Files every chat can read',
        target: 'project-files',
        placement: 'auto',
        body: 'Upload the documents the work needs once, and each chat in the project can read them.',
      },
      {
        id: 'memory',
        title: 'What it remembers',
        target: 'project-memory',
        placement: 'auto',
        body: 'Notes the assistant keeps for this project, written by you or learned along the way. Forget one when it stops being true.',
      },
    ],
  },
  {
    id: 'prompt-libraries',
    area: 'Chat',
    version: 1,
    title: 'Prompt libraries',
    description: 'Keeping the prompts you reuse, and sharing them.',
    startPath: '/chat/prompts',
    autoStart: true,
    requires: ['prompts-new'],
    audience: 'everyone',
    steps: [
      {
        id: 'new',
        title: 'Make a library',
        target: 'prompts-new',
        placement: 'bottom',
        body: 'A library is a named set of prompts. Insert one into any chat from the composer, or by typing a slash into an empty box.',
      },
      {
        id: 'shared',
        title: 'Yours, and shared with you',
        body: 'Libraries colleagues shared with you are listed under your own. A shared library can be read-only or editable, as its owner chose.',
      },
    ],
  },
  {
    id: 'prompt-library',
    area: 'Chat',
    version: 1,
    title: 'Inside a library',
    description: 'Adding a prompt, and sharing the library.',
    startPath: '/chat/prompts',
    autoStart: true,
    requires: ['library-new-prompt'],
    audience: 'everyone',
    steps: [
      {
        id: 'add',
        title: 'Add a prompt',
        target: 'library-new-prompt',
        placement: 'auto',
        body: 'New prompt asks for a title to pick it by and the prompt text itself. Edit or delete a prompt from its row.',
      },
      {
        id: 'share',
        title: 'Share the library',
        target: 'library-share',
        placement: 'bottom',
        body: 'Give colleagues read or edit access for a while. They see the library under Shared with me.',
      },
    ],
  },
  {
    id: 'memory',
    area: 'Chat',
    version: 1,
    title: 'Memory',
    description: 'What the assistant remembers about you across chats.',
    startPath: '/chat/memory',
    autoStart: true,
    requires: ['memory-add'],
    audience: 'everyone',
    steps: [
      {
        id: 'add',
        title: 'Tell it something to keep',
        target: 'memory-add',
        placement: 'top',
        body: 'A note here is read by every chat you start: your role, how you like answers, the projects you work on. The assistant adds notes of its own as it learns; edit or forget any of them.',
      },
    ],
  },
  {
    id: 'code',
    area: 'Chat',
    version: 1,
    title: 'Code projects',
    description: 'A repository to work in, with chats that can read and change it.',
    startPath: '/code',
    autoStart: true,
    requires: ['code-new'],
    audience: 'everyone',
    steps: [
      {
        id: 'new',
        title: 'Start from a repository',
        target: 'code-new',
        placement: 'bottom',
        body: 'A code project checks a repository out into a workspace. Its chats read the code, run the tests, and make changes you review before they are pushed.',
      },
    ],
  },
  {
    id: 'code-new',
    area: 'Chat',
    version: 1,
    title: 'A new code project',
    description: 'Choosing the repository and briefing the assistant.',
    startPath: '/code/new',
    autoStart: true,
    requires: ['code-repo-search'],
    audience: 'everyone',
    steps: [
      {
        id: 'repo',
        title: 'Pick the repository',
        target: 'code-repo-search',
        placement: 'auto',
        body: 'Search the repositories your account can reach and pick one; the branch and a name follow. Or make a new, empty repository to start from.',
      },
      {
        id: 'instructions',
        title: 'The standing brief',
        target: 'code-instructions',
        placement: 'auto',
        body: 'How to run the tests, the conventions to keep, what not to touch. Every chat in the project reads this first; change it here or on the project page later.',
      },
    ],
  },
];
