import type { CoachMarkTour } from '../types';

/**
 * The Connectors page, the catalog behind Add connector, and one tour per
 * product card.
 *
 * The card tours do not start unasked: a page with six cards would
 * otherwise greet every visit with the next one. They run from the
 * Tutorials page, from a `?tour=` link, and each is pinned to its own
 * card, so a product the organization has not offered this person has no
 * tour to offer either. The controls a first connection goes through (the
 * capability picker, the Connect button) are gone once connected; a step
 * about one then shows centred and reads as a reminder.
 */
export const CONNECTOR_TOURS: CoachMarkTour[] = [
  {
    id: 'connectors',
    area: 'Connectors',
    version: 1,
    title: 'Connectors',
    description: 'Connecting your own accounts, and the endpoint your LLM app talks to.',
    startPath: '/connectors',
    autoStart: true,
    requires: ['connectors-add'],
    audience: 'everyone',
    steps: [
      {
        id: 'add',
        title: 'Connect your accounts',
        target: 'connectors-add',
        placement: 'bottom',
        body: 'Pick the tools you work with. Each one connects with your own credentials, so everything Renkei does in it happens as you and sees only what you can see.',
      },
      {
        id: 'endpoint',
        title: 'Your MCP endpoint',
        target: 'connectors-endpoint',
        placement: 'bottom',
        body: 'Paste this URL into an LLM app that speaks MCP and it gains the same tools, with the same permissions, as your chat here.',
      },
      {
        id: 'cards',
        title: 'One card per product',
        body: 'Each product you add gets a card below, with what Renkei may do in it and a Connect button. Every card has a tour of its own under Tutorials, in the account menu.',
      },
    ],
  },
  {
    id: 'add-connector',
    area: 'Connectors',
    version: 1,
    title: 'Adding a connector',
    description: 'The catalog behind Add connector. Starts the first time you open it.',
    startPath: '/connectors',
    // Greets the first opening of the catalog — the anchor exists only
    // while the modal is up, so that is the only time it can.
    autoStart: true,
    requires: ['connectors-search'],
    audience: 'everyone',
    steps: [
      {
        id: 'search',
        title: 'Find the tool',
        target: 'connectors-search',
        placement: 'bottom',
        body: 'Search by name or by what you want to do — “email”, “tickets”, “meetings”. What is listed is what your organization has set up for you.',
      },
      {
        id: 'add',
        title: 'Add puts the card on your page',
        target: 'connectors-catalog',
        placement: 'auto',
        body: 'Add only places the card. Nothing connects until you press Connect on it, and a card you never connect can be removed again from its foot.',
      },
    ],
  },
  {
    id: 'connect-jira',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Jira',
    description: 'Choosing what Renkei may do in Jira, and connecting as yourself.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-jira'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Jira, as you',
        target: 'card-jira',
        placement: 'auto',
        body: 'Issues, boards, sprints, comments and worklogs — read and, when you ask, changed — in the projects your Jira account can see. Jira is one of four separate Atlassian connections on this card; each connects on its own.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'jira-scopes',
        placement: 'auto',
        body: 'Your organization sets the most Renkei may ask for; uncheck anything you do not want it to have. A capability left unchecked has no tools at all. Reconnect later to change it.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'jira-connect',
        placement: 'auto',
        body: 'Atlassian asks you to approve exactly what you checked, then sends you back here connected. Disconnect, on the same panel, revokes it and every MCP client token issued for you.',
      },
    ],
  },
  {
    id: 'connect-jsm',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Jira Service Management',
    description: 'Service desk requests, alerts and on-call, on a consent of their own.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-jsm'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'A separate Atlassian consent',
        target: 'card-jsm',
        placement: 'auto',
        body: 'Service desk requests, customers, SLAs, alerts, schedules and who is on call. Atlassian cannot fit these on the Jira consent, so Service Management connects on its own even if Jira already is.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'jsm-scopes',
        placement: 'auto',
        body: 'The same picker as Jira: the organization’s ceiling, narrowed by you. Operations — alerts and on-call — is its own group, easy to leave out if you only file requests.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'jsm-connect',
        placement: 'auto',
        body: 'Approve on Atlassian’s screen and come back connected. Disconnecting Service Management leaves Jira as it was.',
      },
    ],
  },
  {
    id: 'connect-confluence',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Confluence',
    description: 'Spaces, pages and comments, read and written as you.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-confluence'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Confluence, as you',
        target: 'card-confluence',
        placement: 'auto',
        body: 'Spaces, pages, blog posts, comments, labels, tasks, attachments, databases and whiteboards — everything your Confluence account can see. A different product from Jira, so a connection of its own.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'confluence-scopes',
        placement: 'auto',
        body: 'Reading is one set of capabilities; creating and editing pages another. Leave writing unchecked and the assistant can only ever read.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'confluence-connect',
        placement: 'auto',
        body: 'Approve on Atlassian’s screen and come back connected. Once connected, a space can be watched so its pages join knowledge search.',
      },
    ],
  },
  {
    id: 'connect-jira-admin',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Jira Administration',
    description: 'Jira’s configuration and Plans, for Jira admins, on a connection of its own.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-jira-admin'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'For Jira admins',
        target: 'card-jira-admin',
        placement: 'auto',
        body: 'Custom fields and their options, how each space is configured, and Plans. It is a separate Atlassian app from Jira, and only useful if you administer Jira or a space — Jira still checks that on every call.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'jira-admin-scopes',
        placement: 'auto',
        body: 'Jira’s administration permissions are broad, so reading configuration already takes them. Nothing about Jira changes from here without you applying it in Renkei.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'jira-admin-connect',
        placement: 'auto',
        body: 'Approve on Atlassian’s screen and come back connected. Disconnecting it leaves your everyday Jira connection as it was.',
      },
    ],
  },
  {
    id: 'connect-bitbucket',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Bitbucket',
    description: 'Repositories, pull requests and pipelines, with your Bitbucket account.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-bitbucket'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Bitbucket Cloud, as you',
        target: 'card-bitbucket',
        placement: 'auto',
        body: 'Repositories, branches, commits, code search, pull requests and pipelines. Bitbucket has an OAuth system of its own, apart from the rest of Atlassian, so it connects separately.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'bitbucket-scopes',
        placement: 'auto',
        body: 'Bitbucket’s consent screen shows the app’s whole set whatever you pick here; what you leave unchecked is enforced by Renkei — those tools never appear.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'bitbucket-connect',
        placement: 'auto',
        body: 'Approve on Bitbucket’s screen and come back connected. Code projects under Chat can then check out any repository your account can reach.',
      },
    ],
  },
  {
    id: 'connect-github',
    area: 'Connectors',
    version: 1,
    title: 'Connecting GitHub',
    description: 'Repositories, pull requests and Actions, with your GitHub account.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-github'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'GitHub, as you',
        target: 'card-github',
        placement: 'auto',
        body: 'Repositories, branches, commits, code search, pull requests and Actions — for any organization or account where Renkei’s GitHub App is installed and you have access.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'github-scopes',
        placement: 'auto',
        body: 'GitHub’s own permissions are fixed on the App whatever you pick here; what you leave unchecked is enforced by Renkei — those tools never appear.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'github-connect',
        placement: 'auto',
        body: 'Approve on GitHub’s screen (installing the App first if it isn’t already) and come back connected. Code projects under Chat can then check out any repository your account can reach.',
      },
    ],
  },
  {
    id: 'connect-microsoft',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Microsoft 365',
    description: 'Outlook, SharePoint and OneDrive on one consent, and what Outlook indexes.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-microsoft'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'One consent for every product',
        target: 'card-microsoft',
        placement: 'auto',
        body: 'Unlike Atlassian, Microsoft asks once for all of it: mail, calendar and tasks in Outlook, documents in SharePoint and OneDrive, and the directory.',
      },
      {
        id: 'products',
        title: 'Choose per product',
        target: 'microsoft-products',
        placement: 'auto',
        body: 'Each product panel has its own capabilities; the connection below sends all of them in a single approval. A product whose capabilities the organization has not allowed is not shown.',
      },
      {
        id: 'connect',
        title: 'Connect, or re-authorize',
        target: 'microsoft-connect',
        placement: 'auto',
        body: 'Microsoft asks for exactly what is checked. Change a checkbox later and the button becomes Approve changes: Microsoft keeps the old permissions until you approve the new set.',
      },
      {
        id: 'indexing',
        title: 'What Outlook indexes',
        target: 'outlook-indexing',
        placement: 'auto',
        body: 'Once connected, your mail and calendar power the tools straight away, but nothing is indexed into knowledge search until you opt in here, category by category.',
      },
    ],
  },
  {
    id: 'connect-webex',
    area: 'Connectors',
    version: 1,
    title: 'Connecting WebEx',
    description: 'Rooms, messages and meetings as you, and watching all your spaces.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-webex'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'WebEx, as you',
        target: 'card-webex',
        placement: 'auto',
        body: 'Read your rooms, messages, meeting transcripts and recordings; capture a message as an actionable item; send a message as you when you explicitly ask.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'webex-scopes',
        placement: 'auto',
        body: 'Sending is its own capability. Leave it unchecked and the assistant can read everything you can, and post nothing.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'webex-connect',
        placement: 'auto',
        body: 'Approve on WebEx’s screen and come back connected. Disconnect, on the same card, revokes it.',
      },
      {
        id: 'spaces',
        title: 'Watch all my spaces',
        target: 'webex-watch-spaces',
        placement: 'auto',
        body: 'Once connected, this switch registers a webhook on your account covering every space you are in, so agents with a message trigger react in real time and messages join knowledge — readable only by the people currently in that space.',
      },
    ],
  },
  {
    id: 'connect-zoom',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Zoom',
    description: 'Meetings, recordings, transcripts and AI Companion summaries as you.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-zoom'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Zoom, as you',
        target: 'card-zoom',
        placement: 'auto',
        body: 'Read your meetings, recordings, transcripts and AI Companion summaries; bring a transcript into knowledge; schedule or manage a meeting when you ask.',
      },
      {
        id: 'scopes',
        title: 'What Renkei may do',
        target: 'zoom-scopes',
        placement: 'auto',
        body: 'Zoom only grants scopes the organization’s Marketplace app carries. If a capability you checked comes back ungranted, the card says so after connecting, and the tools that need it stay off.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'zoom-connect',
        placement: 'auto',
        body: 'Approve on Zoom’s screen and come back connected. Disconnect and reconnect after the organization adds a missing scope.',
      },
    ],
  },
  {
    id: 'connect-onbase',
    area: 'Connectors',
    version: 1,
    title: 'Connecting OnBase',
    description: 'Document search, reading and filing with your OnBase account.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-onbase'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'OnBase, as you',
        target: 'card-onbase',
        placement: 'auto',
        body: 'Search by keywords or saved custom queries, read documents and their history, upload and index new ones — everything OnBase lets your account see, and nothing more. No capability picker: OnBase grants what your account has.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'onbase-connect',
        placement: 'auto',
        body: 'You sign in on your organization’s own Hyland identity provider and come back connected. OnBase Administration, below, is a separate connection for configuring document types.',
      },
    ],
  },
  {
    id: 'connect-onbase-admin',
    area: 'Connectors',
    version: 1,
    title: 'Connecting OnBase Administration',
    description: 'Configuring document and keyword types, on a connection of its own.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-onbase-admin'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'The configuration side of OnBase',
        target: 'card-onbase-admin',
        placement: 'auto',
        body: 'Create and update document types and keyword types, and change which keywords a document type carries. A different Hyland client from document access, so it connects separately.',
      },
      {
        id: 'connect',
        title: 'Connect',
        target: 'onbase-admin-connect',
        placement: 'auto',
        body: 'The same Hyland sign-in as OnBase. What you can configure is what your OnBase account may configure.',
      },
    ],
  },
  {
    id: 'connect-fileshares',
    area: 'Connectors',
    version: 1,
    title: 'Connecting a file share',
    description: 'Network shares, each connected with your own file-server account.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-fileshares'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Your organization’s shares',
        target: 'card-fileshares',
        placement: 'auto',
        body: 'SMB and SFTP shares an operator registered. Each connects with your own account on that server, so what Renkei can reach there is what you can.',
      },
      {
        id: 'list',
        title: 'Connect each share',
        target: 'fileshares-list',
        placement: 'auto',
        body: 'Connect asks for your username and password for that share. Once connected, the checkboxes say whether the assistant may write or delete there; the server still has the final say. Browse what you connected under Files.',
      },
    ],
  },
  {
    id: 'connect-mirth',
    area: 'Connectors',
    version: 1,
    title: 'Connecting Mirth Connect',
    description: 'Integration engines, each connected with your own Mirth account.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-mirth'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Your organization’s Mirth servers',
        target: 'card-mirth',
        placement: 'auto',
        body: 'One entry per instance an operator registered — dev, test, prod. Each connects with your own Mirth account, so what Renkei can do there is what you can.',
      },
      {
        id: 'list',
        title: 'Connect each instance',
        target: 'mirth-list',
        placement: 'auto',
        body: 'Connect asks for your Mirth username and password and which permissions the tools get — a preset, or your own set. Change permissions later from the same row; Mirth still has the final say.',
      },
    ],
  },
  {
    id: 'browser-secrets',
    area: 'Connectors',
    version: 1,
    title: 'Browser secrets',
    description: 'Logins the sandbox browser may type for an agent, without the model seeing them.',
    startPath: '/connectors',
    autoStart: false,
    requires: ['card-secrets'],
    audience: 'everyone',
    steps: [
      {
        id: 'card',
        title: 'Logins the model never sees',
        target: 'card-secrets',
        placement: 'auto',
        body: 'An agent’s sandbox browser can sign in to a named site with a secret kept here. The model only learns that the secret exists; the value is typed by the sandbox, on the hosts you allow.',
      },
      {
        id: 'add',
        title: 'Add a secret',
        target: 'secrets-add',
        placement: 'auto',
        body: 'A name the agent refers to, the hosts it may be typed on, and its fields. Each secret is sealed under a passphrase shown once — Renkei does not keep it — stays unlocked only for the window you choose, and expires on its own.',
      },
    ],
  },
];
