import type { CoachMarkTour } from '../types';

/**
 * The operator console — every tour here is for operators only, and each
 * greets the first visit to its area. An area's tour is pinned to the
 * control that makes the area what it is (the search box, the "+ New"
 * link, the master switch), so it belongs on that page and nowhere else.
 */
export const ORGANIZATION_TOURS: CoachMarkTour[] = [
  {
    id: 'admin',
    area: 'Organization',
    version: 1,
    title: 'The organization console',
    description: 'For operators: what each area of the console is for.',
    startPath: '/admin',
    autoStart: true,
    requires: ['admin-sections'],
    audience: 'operators',
    steps: [
      {
        id: 'areas',
        title: 'Everything an operator configures',
        target: 'admin-sections',
        placement: 'top',
        body: 'Connections hold app registrations and credentials; Agents oversees every agent in the organization; Usage and the records below show who is doing what. Tutorials, under People and records, reports on who has taken these tours.',
      },
    ],
  },
  {
    id: 'admin-connectors',
    area: 'Organization',
    version: 1,
    title: 'Connector setup',
    description:
      'What the organization runs, with what credentials, and the switch that stops a connector being offered.',
    startPath: '/admin/connectors',
    autoStart: true,
    requires: ['admin-connectors-search'],
    audience: 'operators',
    steps: [
      {
        id: 'search',
        title: 'Every connector Renkei knows',
        target: 'admin-connectors-search',
        placement: 'bottom',
        body: 'The whole catalog, whether or not it is set up here. Find one by name or by what it does.',
      },
      {
        id: 'list',
        title: 'Set up, offered, or off',
        target: 'admin-connectors-list',
        placement: 'auto',
        body: 'Each row says whether the connector has credentials registered and whether it is offered. Open a row to register its app and secrets; its switch takes the tools away from everyone at once without touching anyone’s connection.',
      },
      {
        id: 'people',
        title: 'People connect for themselves',
        body: 'Registering a connector here only provisions it. Each person then connects their own account from their Connectors page, where it appears in the catalog once it is enabled.',
      },
    ],
  },
  {
    id: 'admin-connector-detail',
    area: 'Organization',
    version: 1,
    title: 'A connector’s page',
    description: 'Registering its app and secrets, and choosing who it is offered to.',
    startPath: '/admin/connectors',
    autoStart: true,
    requires: ['admin-connector-form'],
    audience: 'operators',
    steps: [
      {
        id: 'form',
        title: 'The registration',
        target: 'admin-connector-form',
        placement: 'auto',
        body: 'The app registration the provider gave you — client id, secret, tenant or site — and the most any person may grant: the scope ceiling their own picker narrows. Secrets are sealed on save and never shown again.',
      },
      {
        id: 'availability',
        title: 'Offered to everyone',
        target: 'admin-connector-availability',
        placement: 'auto',
        body: 'Off stops the tools being offered to anyone, immediately. Nobody’s connection changes and nobody reconnects; on restores them as they were.',
      },
      {
        id: 'audience',
        title: 'Or only to some',
        target: 'admin-connector-audience',
        placement: 'auto',
        body: 'Name the identity-provider groups a product is for and it appears in the catalog only for their members. Empty means everyone.',
      },
    ],
  },
  {
    id: 'admin-file-shares',
    area: 'Organization',
    version: 1,
    title: 'File shares',
    description: 'Registering the network shares people may connect to.',
    startPath: '/admin/file-shares',
    autoStart: true,
    requires: ['admin-shares-new'],
    audience: 'operators',
    steps: [
      {
        id: 'new',
        title: 'Register a share',
        target: 'admin-shares-new',
        placement: 'bottom',
        body: 'Where it is — SMB or SFTP, host and share name — and a service credential Renkei uses to check it. People connect it with their own account afterwards.',
      },
      {
        id: 'list',
        title: 'Manage a share',
        target: 'admin-shares-list',
        placement: 'auto',
        body: 'A share’s page grants access per person — without a grant nobody can even see it exists — and can narrow each person to particular folders.',
      },
    ],
  },
  {
    id: 'admin-mirth',
    area: 'Organization',
    version: 1,
    title: 'Mirth Connect',
    description: 'Registering the integration engines people may connect to.',
    startPath: '/admin/mirth',
    autoStart: true,
    requires: ['admin-mirth-new'],
    audience: 'operators',
    steps: [
      {
        id: 'new',
        title: 'Register an instance',
        target: 'admin-mirth-new',
        placement: 'bottom',
        body: 'Its name, environment and base URL, and whether to verify its TLS certificate. Probe it before saving to be sure Renkei can reach it.',
      },
      {
        id: 'list',
        title: 'What people see',
        target: 'admin-mirth-list',
        placement: 'auto',
        body: 'Every enabled instance is offered on the Connectors page; each person connects with their own Mirth account, and the server’s own roles decide what that account may do.',
      },
    ],
  },
  {
    id: 'admin-sites',
    area: 'Organization',
    version: 1,
    title: 'Sites',
    description: 'The external places the organization reaches, and what is indexed.',
    startPath: '/admin/sites',
    autoStart: true,
    requires: ['admin-sites-atlassian'],
    audience: 'operators',
    steps: [
      {
        id: 'atlassian',
        title: 'Atlassian sites',
        target: 'admin-sites-atlassian',
        placement: 'auto',
        body: 'Derived, not configured: a site appears when someone connects Jira, Service Management or Confluence, with the products and the accounts connected to it.',
      },
      {
        id: 'indexed',
        title: 'Indexed for knowledge search',
        target: 'admin-sites-indexed',
        placement: 'auto',
        body: 'Every watch people set up — a Jira project, a Confluence space, a SharePoint library — and the state of its indexing. Access stays per reader; this is the inventory.',
      },
    ],
  },
  {
    id: 'admin-models',
    area: 'Organization',
    version: 1,
    title: 'Agent models',
    description: 'The models agents run on, with the organization’s own API keys.',
    startPath: '/admin/llm-models',
    autoStart: true,
    requires: ['admin-models-add'],
    audience: 'operators',
    steps: [
      {
        id: 'add',
        title: 'Add a model',
        target: 'admin-models-add',
        placement: 'bottom',
        body: 'A provider, a model name and an API key — yours, or one the deployment holds. Without at least one enabled model, agents cannot run and saved-agent summaries are not generated.',
      },
      {
        id: 'list',
        title: 'The default, and the rest',
        target: 'admin-models-list',
        placement: 'auto',
        body: 'Agents use the default unless their owner picks another from this list. Disable a model to take it away without deleting it; “no key stored” means it cannot run yet.',
      },
    ],
  },
  {
    id: 'admin-storage',
    area: 'Organization',
    version: 1,
    title: 'Storage',
    description: 'Where attachments and the assistant’s files live.',
    startPath: '/admin/storage',
    autoStart: true,
    requires: ['admin-storage-form'],
    audience: 'operators',
    steps: [
      {
        id: 'form',
        title: 'Azure Blob Storage',
        target: 'admin-storage-form',
        placement: 'auto',
        body: 'The account and container for what people attach to chats and projects and what the assistant produces. The key is sealed on save. Without storage, uploads are off and the assistant is told not to produce files.',
      },
    ],
  },
  {
    id: 'admin-agents',
    area: 'Organization',
    version: 1,
    title: 'Agent oversight',
    description:
      'Every agent in the organization: runs, failures, tokens, and how long history is kept.',
    startPath: '/admin/agents',
    autoStart: true,
    requires: ['admin-oversight-controls'],
    audience: 'operators',
    steps: [
      {
        id: 'controls',
        title: 'Pick a period, then sort',
        target: 'admin-oversight-controls',
        placement: 'bottom',
        body: 'Today, this week or this month; sort by runs, failures or tokens to find the agent that is misbehaving or expensive.',
      },
      {
        id: 'org',
        title: 'The whole organization',
        target: 'admin-oversight-org',
        placement: 'auto',
        body: 'Runs and failures across every agent, and tokens by model, against the daily cap. Each agent card below opens a page that breaks its spend down by model and by step; you can turn an agent off, but editing stays with its owner.',
      },
      {
        id: 'retention',
        title: 'How long runs are kept',
        target: 'admin-oversight-retention',
        placement: 'top',
        body: 'Run records, step details included, are deleted after this many days. Shorter keeps less of what tools returned around.',
      },
    ],
  },
  {
    id: 'admin-calendars',
    area: 'Organization',
    version: 1,
    title: 'Holiday calendars',
    description: 'Blackout dates that agent schedules can skip.',
    startPath: '/admin/calendars',
    autoStart: true,
    requires: ['admin-calendars-new'],
    audience: 'operators',
    steps: [
      {
        id: 'new',
        title: 'Name a set of dates',
        target: 'admin-calendars-new',
        placement: 'bottom',
        body: 'Single days, ranges, or a day every year. A schedule that opts into the calendar skips or shifts runs landing on them, by its own policy.',
      },
      {
        id: 'list',
        title: 'Changes apply going forward',
        target: 'admin-calendars-list',
        placement: 'auto',
        body: 'Editing a calendar affects each schedule from its next computation, not a run already on the clock.',
      },
    ],
  },
  {
    id: 'admin-usage',
    area: 'Organization',
    version: 1,
    title: 'Organization usage',
    description: 'Token spend across the tenant, and who is driving it.',
    startPath: '/admin/usage',
    autoStart: true,
    requires: ['admin-usage-period'],
    audience: 'operators',
    steps: [
      {
        id: 'period',
        title: 'Pick a window',
        target: 'admin-usage-period',
        placement: 'bottom',
        body: 'Every surface and model — chat, projects, code projects, agents — for the period, with how much of the organization is actually using it. Counts only, never content.',
      },
      {
        id: 'person',
        title: 'One person',
        target: 'admin-usage-person',
        placement: 'bottom',
        body: 'The same picture for one person alone, with their groups and agents. The top-users list can include or exclude agents’ spend.',
      },
    ],
  },
  {
    id: 'admin-redaction',
    area: 'Organization',
    version: 1,
    title: 'Sensitive data',
    description: 'Replacing identifiers in tool results before a model sees them.',
    startPath: '/admin/redaction',
    autoStart: true,
    requires: ['admin-redaction-master'],
    audience: 'operators',
    steps: [
      {
        id: 'master',
        title: 'Filter tool results',
        target: 'admin-redaction-master',
        placement: 'bottom',
        body: 'The master switch. Tools always run and always return; this changes only the text a model receives. Replacement is consistent, so the same record number becomes the same stand-in every time.',
      },
      {
        id: 'detectors',
        title: 'What to look for',
        target: 'admin-redaction-detectors',
        placement: 'auto',
        body: 'Each detector is a kind of identifier — names, dates, numbers, contact details. Turn on the ones your data carries.',
      },
      {
        id: 'formats',
        title: 'Record number formats',
        body: 'Below: one pattern per line for the record numbers your own systems write without a label, so they are caught too.',
      },
    ],
  },
  {
    id: 'admin-email-sanitizer',
    area: 'Organization',
    version: 1,
    title: 'Email sanitizer',
    description: 'Classifying mail before it is indexed, and stripping its boilerplate.',
    startPath: '/admin/email-sanitizer',
    autoStart: true,
    requires: ['admin-sanitizer-rules'],
    audience: 'operators',
    steps: [
      {
        id: 'rules',
        title: 'Classifier rules',
        target: 'admin-sanitizer-rules',
        placement: 'auto',
        body: 'Which senders, addresses or subjects count as system notifications or marketing, in priority order; the first enabled match wins. Mail matching nothing is treated as human correspondence and never dropped.',
      },
      {
        id: 'scripts',
        title: 'Cleaner scripts',
        target: 'admin-sanitizer-scripts',
        placement: 'auto',
        body: 'Where boilerplate removal happens: a small function over a body before it is indexed, run in a sealed sandbox. A failing script never loses anything — the text passes through unchanged and the error shows here.',
      },
    ],
  },
  {
    id: 'admin-settings',
    area: 'Organization',
    version: 1,
    title: 'Settings',
    description: 'Organization-wide controls, and the two brakes.',
    startPath: '/admin/settings',
    autoStart: true,
    requires: ['admin-settings-safety'],
    audience: 'operators',
    steps: [
      {
        id: 'safety',
        title: 'The brakes',
        target: 'admin-settings-safety',
        placement: 'auto',
        body: 'Read-only mode hides every tool that changes an external system, org-wide and at once. Guided tours takes every tour, this one included, down for everyone — the escape hatch if a tour misbehaves.',
      },
      {
        id: 'sections',
        title: 'Everything else',
        body: 'Agents: the daily token cap and what agents may do. Data and logs: retention and log level. Knowledge search, MCP clients and tokens, and request limits follow.',
      },
      {
        id: 'save',
        title: 'Saved together',
        target: 'admin-settings-save',
        placement: 'top',
        body: 'Nothing above applies until saved. Changes take effect within a minute and are recorded in the audit trail.',
      },
      {
        id: 'identity',
        title: 'Identity',
        target: 'admin-settings-identity',
        placement: 'auto',
        body: 'How people sign in, and which claims carry their role and groups — the groups that connector audiences and share grants refer to.',
      },
    ],
  },
  {
    id: 'admin-access',
    area: 'Organization',
    version: 1,
    title: 'Access',
    description: 'Who is connected to what, and cutting a connection.',
    startPath: '/admin/access',
    autoStart: true,
    requires: ['admin-access-table'],
    audience: 'operators',
    steps: [
      {
        id: 'table',
        title: 'Everyone, and their connectors',
        target: 'admin-access-table',
        placement: 'auto',
        body: 'Everyone who has signed in or linked an account, with each connector they hold. Disconnect cuts Renkei’s access immediately; the person can reconnect any time. Their usage, groups and agents are on Organization usage.',
      },
    ],
  },
  {
    id: 'admin-audit',
    area: 'Organization',
    version: 1,
    title: 'Audit',
    description: 'Platform actions in the organization, day by day.',
    startPath: '/admin/audit',
    autoStart: true,
    requires: ['admin-audit-list'],
    audience: 'operators',
    steps: [
      {
        id: 'list',
        title: 'What changed, and who changed it',
        target: 'admin-audit-list',
        placement: 'auto',
        body: 'Sign-ins, connector changes, agent changes and settings, newest first. Tool usage is not here; that is the Tools page, and each person’s own Activity.',
      },
    ],
  },
  {
    id: 'admin-events',
    area: 'Organization',
    version: 1,
    title: 'Events',
    description: 'Incoming webhooks and internal events, and how each resolved.',
    startPath: '/admin/events',
    autoStart: true,
    requires: ['admin-events-list'],
    audience: 'operators',
    steps: [
      {
        id: 'filters',
        title: 'By outcome',
        target: 'admin-events-filters',
        placement: 'bottom',
        body: 'Processed, retrying, dead-lettered: the pills narrow the list to one outcome. A dead letter is an event that was given up on, and the place to start when a trigger did not fire.',
      },
      {
        id: 'table',
        title: 'Where it came from, where it went',
        target: 'admin-events-list',
        placement: 'auto',
        body: 'Each row: when it arrived, its source, whose it is, what it was handed to, and how it ended. Payloads are summarized, never shown whole.',
      },
    ],
  },
  {
    id: 'admin-tutorials',
    area: 'Organization',
    version: 1,
    title: 'The tutorials report',
    description: 'Who has taken the guided tours, finished them, or skipped.',
    startPath: '/admin/tutorials',
    autoStart: true,
    requires: ['admin-tutorials-tours'],
    audience: 'operators',
    steps: [
      {
        id: 'tours',
        title: 'By tour',
        target: 'admin-tutorials-tours',
        placement: 'auto',
        body: 'For every tour: how many people viewed it, finished it, or skipped it. A tour that is mostly skipped is telling you something about its copy or its timing.',
      },
      {
        id: 'people',
        title: 'By person',
        target: 'admin-tutorials-people',
        placement: 'auto',
        body: 'A person counts once per tour, by how their latest pass ended. The chips say which tours each person has seen — useful before walking someone through a page in person.',
      },
    ],
  },
];
