import type { CoachMarkTour } from '../types';

/** Agents, their runs, knowledge search and the files browser. */
export const WORKSPACE_TOURS: CoachMarkTour[] = [
  {
    id: 'agents',
    area: 'Workspace',
    version: 1,
    title: 'Agents',
    description: 'How to create an agent, import one, and what each listed agent can do.',
    startPath: '/agents',
    autoStart: true,
    requires: ['agents-new'],
    audience: 'everyone',
    steps: [
      {
        id: 'new',
        title: 'Make a new agent',
        target: 'agents-new',
        placement: 'bottom',
        body: 'An agent is a sequence of steps you write in plain words: search these issues, pick the actionable ones, file a ticket. It runs on your own connections and on triggers you set.',
      },
      {
        id: 'import',
        title: 'Or bring one in',
        target: 'agents-import',
        placement: 'bottom',
        body: 'Import an agent a colleague exported, then adjust it as your own.',
      },
      {
        id: 'list',
        title: 'Your agents',
        target: 'agents-list',
        placement: 'top',
        body: 'Each card shows what the agent does and when it runs. Use the switch to pause it, and the icons to run it now, edit its steps, or open its run history.',
      },
    ],
  },
  {
    id: 'agent-builder',
    area: 'Workspace',
    version: 1,
    title: 'The agent builder',
    description: 'Naming an agent, laying out its steps, giving it a trigger, and saving it.',
    startPath: '/agents/new',
    autoStart: true,
    requires: ['builder-name', 'builder-save'],
    audience: 'everyone',
    steps: [
      {
        id: 'name',
        title: 'Name it',
        target: 'builder-name',
        placement: 'bottom',
        body: 'A short name for what the agent does. Its description is written for you from the steps when you save, so this is the one thing you have to word yourself.',
      },
      {
        id: 'canvas',
        title: 'The steps, as a flow',
        target: 'builder-canvas',
        placement: 'auto',
        body: 'Each step is an instruction in plain words, with the tool it may use. Branches decide, loops repeat over a list, groups keep related steps together. Click a step to edit it.',
      },
      {
        id: 'add',
        title: 'Add between any two',
        target: 'builder-add',
        placement: 'auto',
        body: 'The plus between nodes adds a step, a branch or a loop right there. Drag a step to move it.',
      },
      {
        id: 'triggers',
        title: 'When it runs',
        target: 'builder-triggers',
        placement: 'auto',
        body: 'A schedule, an event from a connector, or another agent finishing. An agent with no trigger only runs when you press Run now.',
      },
      {
        id: 'save',
        title: 'Save, then turn it on',
        target: 'builder-save',
        placement: 'top',
        body: 'Saving checks the steps and writes the description. A new agent starts switched off, so you can read it over and run it once by hand before it runs on its own.',
      },
    ],
  },
  {
    id: 'agent-detail',
    area: 'Workspace',
    version: 1,
    title: 'An agent’s page',
    description: 'Editing, sharing and running an agent, and where its history lives.',
    startPath: '/agents',
    autoStart: true,
    requires: ['agent-edit', 'agent-runs-card'],
    audience: 'everyone',
    steps: [
      {
        id: 'edit',
        title: 'Change its steps',
        target: 'agent-edit',
        placement: 'bottom',
        body: 'Edit opens the builder on this agent. Changes take effect on its next run.',
      },
      {
        id: 'share',
        title: 'Share it',
        target: 'agent-share',
        placement: 'bottom',
        body: 'Give a colleague access for a while. They can read and edit it; it still runs as you, on your connections.',
      },
      {
        id: 'run-now',
        title: 'Run it by hand',
        target: 'agent-run-now',
        placement: 'left',
        body: 'Start a run without waiting for the trigger. The run shows up below as it happens.',
      },
      {
        id: 'runs',
        title: 'Its history',
        target: 'agent-runs-card',
        placement: 'left',
        body: 'When it runs, and every run it has made: what each step did, what it called, and where it stopped if it did.',
      },
    ],
  },
  {
    id: 'agent-runs',
    area: 'Workspace',
    version: 1,
    title: 'Run history',
    description: 'Finding a particular run of an agent.',
    startPath: '/agents',
    autoStart: true,
    requires: ['runs-filters', 'runs-search'],
    audience: 'everyone',
    steps: [
      {
        id: 'filters',
        title: 'By how it ended',
        target: 'runs-filters',
        placement: 'bottom',
        body: 'Succeeded, failed, timed out, still running: pick one to see only those.',
      },
      {
        id: 'search',
        title: 'By what it did',
        target: 'runs-search',
        placement: 'bottom',
        body: 'Search the runs by what they wrote and the outcomes they recorded. Open a run for its step-by-step timeline.',
      },
    ],
  },
  {
    id: 'knowledge',
    area: 'Workspace',
    version: 1,
    title: 'Knowledge search',
    description: 'Searching what Renkei has indexed from your connected tools.',
    startPath: '/knowledge',
    autoStart: true,
    requires: ['knowledge-search'],
    audience: 'everyone',
    steps: [
      {
        id: 'search',
        title: 'Ask across your tools',
        target: 'knowledge-search',
        placement: 'bottom',
        body: 'One search over mail, chats, pages, tickets and files Renkei has indexed for you. Filters such as from: and space: narrow it; the help button lists them.',
      },
      {
        id: 'sources',
        title: 'Or pick the sources',
        target: 'knowledge-sources',
        placement: 'bottom',
        body: 'Limit a search to particular connectors. Every result is checked against the source system for your own access before it is shown, so you only ever see what you could open there.',
      },
    ],
  },
  {
    id: 'files',
    area: 'Workspace',
    version: 1,
    title: 'Files',
    description: 'Browsing the organization’s network shares with your own credentials.',
    startPath: '/files',
    autoStart: true,
    requires: ['files-browser'],
    audience: 'everyone',
    steps: [
      {
        id: 'shares',
        title: 'Your shares',
        target: 'files-browser',
        placement: 'bottom',
        body: 'The shares the organization has registered. One you have connected on the Connectors page opens here; the rest wait for your credentials.',
      },
      {
        id: 'toolbar',
        title: 'Inside a share',
        target: 'files-toolbar',
        placement: 'bottom',
        body: 'Filter the folder, keep folders first, make a folder or upload a file. What you may see and change is what your account may on the file server.',
      },
    ],
  },
];
