/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActionableItems {
  archived_at: Timestamp | null;
  archived_by: string | null;
  attempt: number | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  created_by_agent_id: string | null;
  decided_at: Timestamp | null;
  decided_by: string | null;
  evidence: Json;
  id: string;
  iteration: number | null;
  kind: Generated<string>;
  owner_subject: string | null;
  result: Json | null;
  run_id: string | null;
  source: string;
  status: Generated<string>;
  step_id: string | null;
  suggested_action: Json | null;
  summary: string;
  tenant_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentAccessGrants {
  agent_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  grantee_subject: string;
  id: Generated<string>;
  owner_subject: string;
  tenant_id: string;
}

export interface AgentDrafts {
  agent_id: string | null;
  attempts: Generated<number>;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  error_detail: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  owner_subject: string;
  request: Json;
  result: Json | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentJobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  ordering_key: string | null;
  payload: Json;
  run_after: Generated<Timestamp>;
  source: string;
  status: Generated<string>;
  tenant_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentJobsDeadLetters {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dead_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  ordering_key: string | null;
  payload: Json;
  source: string;
  tenant_id: string;
  type: string;
}

export interface AgentMemories {
  agent_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: Generated<string>;
  run_id: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentNotifications {
  agent_id: string | null;
  agent_name: string | null;
  category: string | null;
  connector: string | null;
  created_at: Generated<Timestamp>;
  entity: string | null;
  headline: string;
  id: string;
  kind: string;
  read_at: Timestamp | null;
  ref_id: string | null;
  ref_url: string | null;
  run_id: string | null;
  step_id: string | null;
  subject: string;
  tenant_id: string;
  tool: string | null;
}

export interface AgentOptimizations {
  agent_id: string;
  applied_at: Timestamp | null;
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  error: string | null;
  error_detail: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  input_tokens: Generated<number>;
  output_tokens: Generated<number>;
  owner_subject: string;
  request: Json;
  result: Json | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentRunCounters {
  agent_id: string;
  day: Timestamp;
  failures: Generated<number>;
  input_tokens: Generated<number>;
  output_tokens: Generated<number>;
  runs: Generated<number>;
  tenant_id: string;
}

export interface AgentRunLog {
  agent_id: string;
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  error: string | null;
  error_kind: string | null;
  finished_at: Timestamp | null;
  input_tokens: Generated<number>;
  outcome_code: string | null;
  output_tokens: Generated<number>;
  owner_subject: string;
  run_id: string;
  status: Generated<string>;
  step_id: string | null;
  step_name: string | null;
  steps_version: number | null;
  tenant_id: string;
  tool_calls: Generated<number>;
  trigger_kind: string;
}

export interface AgentRuns {
  agent_id: string;
  cancel_requested_at: Timestamp | null;
  cancel_requested_by: string | null;
  created_at: Generated<Timestamp>;
  current_step_id: string | null;
  depth: Generated<number>;
  error: string | null;
  error_kind: string | null;
  finished_at: Timestamp | null;
  id: string;
  initial_state: Json | null;
  lineage: Generated<Json>;
  llm_model_id: string | null;
  owner_subject: string;
  parent_run_id: string | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  steps_snapshot: Json;
  tenant_id: string;
  trigger_id: string | null;
  trigger_kind: string;
  triggered_by_subject: string | null;
  updated_at: Generated<Timestamp>;
  waiting_until: Timestamp | null;
}

export interface AgentRunSteps {
  attempt: number;
  created_at: Generated<Timestamp>;
  detail: Json | null;
  finished_at: Timestamp | null;
  id: string;
  input_tokens: Generated<number>;
  /** 0 = not inside a loop (all pre-v3 rows); 1-based inside a loop. */
  iteration: Generated<number>;
  outcome: string | null;
  outcome_code: string | null;
  output_tokens: Generated<number>;
  run_id: string;
  started_at: Timestamp | null;
  status: string;
  step_id: string;
  step_index: number;
  tenant_id: string;
  tool_call_count: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Agents {
  blocked_tools: Json | null;
  can_ask_questions: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  description_status: Generated<string>;
  enabled: Generated<boolean>;
  guardrails: string | null;
  id: string;
  llm_model_id: string | null;
  name: string;
  owner_subject: string;
  review_notes: Json | null;
  steps: Json;
  steps_version: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentTriggerFirings {
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  run_id: string | null;
  tenant_id: string;
  trigger_id: string;
}

export interface AgentTriggers {
  agent_id: string;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  event_source: string | null;
  event_type: string | null;
  id: string;
  kind: string;
  last_error: string | null;
  last_fired_at: Timestamp | null;
  next_run_at: Timestamp | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AuditEvents {
  action: string;
  actor_subject: string | null;
  created_at: Generated<Timestamp>;
  details: Json | null;
  id: string;
  target_kind: string | null;
  target_label: string | null;
  tenant_id: string;
}

export interface BatchJobItems {
  batch_id: string;
  created_at: Generated<Timestamp>;
  error: string | null;
  id: string;
  payload: Generated<Json>;
  result: Json | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface BatchJobMessages {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  ordering_key: string | null;
  payload: Json;
  run_after: Generated<Timestamp>;
  source: string;
  status: Generated<string>;
  tenant_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface BatchJobMessagesDeadLetters {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dead_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  ordering_key: string | null;
  payload: Json;
  source: string;
  tenant_id: string;
  type: string;
}

export interface BatchJobs {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  failed: Generated<number>;
  finished_at: Timestamp | null;
  id: string;
  kind: string;
  last_error: string | null;
  name: Generated<string>;
  schedule_id: string | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  subject: string;
  succeeded: Generated<number>;
  tenant_id: string;
  total: number | null;
  updated_at: Generated<Timestamp>;
}

export interface BatchJobSchedules {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: string;
  kind: string;
  last_error: string | null;
  last_fired_at: Timestamp | null;
  name: string;
  next_run_at: Timestamp | null;
  schedule_config: Generated<Json>;
  subject: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ConnectorConfigs {
  connector: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  encrypted_secrets: string;
  settings: Generated<Json>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ContentWatches {
  account_id: string;
  created_at: Generated<Timestamp>;
  cursor: string | null;
  enabled: Generated<boolean>;
  id: string;
  last_error: string | null;
  last_run_items: Generated<number>;
  last_synced_at: Timestamp | null;
  provider: string;
  scope_key: string;
  scope_label: string | null;
  scope_type: string;
  subject: string;
  sync_status: Generated<string>;
  tenant_id: string;
  total_items: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface EmailClassificationLog {
  account_id: string | null;
  category: string;
  content_hash: string | null;
  created_at: Generated<Timestamp>;
  excerpt: string;
  id: string;
  match_score: number | null;
  matched_rule_id: string | null;
  needs_review: Generated<boolean>;
  overridden_at: Timestamp | null;
  override_action: string | null;
  override_category: string | null;
  override_sender_key: string | null;
  owner_upn: string;
  provider: string;
  ref_id: string;
  sender_key: string | null;
  template_id: string | null;
  template_version: number | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EmailClassifierRules {
  category: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: string;
  match_type: string;
  match_value: string;
  priority: Generated<number>;
  sender_key: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EmailCleanerScripts {
  applies_to: Generated<string[]>;
  compiled: string | null;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: string;
  last_error: string | null;
  name: string;
  script: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EmailExtractionTemplates {
  created_at: Generated<Timestamp>;
  derived_by_upn: string;
  id: string;
  match_threshold: Generated<number>;
  sender_key: string;
  spec: Json;
  status: string;
  superseded_at: Timestamp | null;
  tenant_id: string;
  version: number;
}

export interface EmbeddingJobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  ordering_key: string | null;
  payload: Json;
  run_after: Generated<Timestamp>;
  source: string;
  status: Generated<string>;
  tenant_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface EmbeddingJobsDeadLetters {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dead_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  ordering_key: string | null;
  payload: Json;
  source: string;
  tenant_id: string;
  type: string;
}

export interface Events {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  ordering_key: string | null;
  payload: Json;
  run_after: Generated<Timestamp>;
  source: string;
  status: Generated<string>;
  tenant_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface EventsDeadLetters {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dead_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  ordering_key: string | null;
  payload: Json;
  source: string;
  tenant_id: string;
  type: string;
}

export interface FileShareConnections {
  allow_delete: Generated<boolean>;
  created_at: Generated<Timestamp>;
  encrypted_credentials: string;
  share_id: string;
  subject: string;
  tenant_id: string;
  tool_access: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface FileShares {
  case_insensitive: boolean;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  host: string;
  id: Generated<string>;
  name: string;
  port: number | null;
  protocol: string;
  root_path: Generated<string>;
  settings: Generated<Json>;
  share_name: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Identities {
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string;
  subject: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface JiraSessions {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  ip_address: string | null;
  last_used_at: Timestamp;
  tenant_id: string;
  user_agent: string | null;
}

export interface KnowledgeChunks {
  content: string;
  created_at: Generated<Timestamp>;
  embedding: string;
  id: string;
  keywords: string[] | null;
  metadata: Generated<Json>;
  provider: string;
  ref_id: string;
  search_text: string | null;
  source_at: Timestamp | null;
  tenant_id: string;
}

export interface KnowledgeReindexRuns {
  created_at: Generated<Timestamp>;
  cursor: string | null;
  failed: Generated<number>;
  finished_at: Timestamp | null;
  id: string;
  kind: string;
  last_error: string | null;
  processed: Generated<number>;
  requested_by: string | null;
  skipped: Generated<number>;
  started_at: Timestamp | null;
  status: Generated<string>;
  tenant_id: string;
}

export interface LlmCalls {
  agent_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  input_tokens: Generated<number>;
  output_tokens: Generated<number>;
  purpose: string;
  run_id: string | null;
  step_id: string | null;
  subject: string;
  tenant_id: string;
}

export interface LlmModelConfigs {
  base_url: string | null;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  encrypted_secrets: string;
  id: string;
  is_default: Generated<boolean>;
  label: string;
  model: string;
  provider: string;
  settings: Generated<Json>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface LogAttr {
  attr_id: Generated<Int8>;
  encrypted: Generated<boolean>;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  val: string | null;
  val_name: string;
  val_type: string;
}

export interface LogAttrBlob {
  attr_id: Generated<Int8>;
  encrypted: Generated<boolean>;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  val: Buffer;
  val_name: string;
}

export interface Logs {
  level: string;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  message: string;
}

export interface MailBulkJobs {
  account_id: string;
  action: string;
  created_at: Generated<Timestamp>;
  failed: Generated<number>;
  failures: Generated<Json>;
  finished_at: Timestamp | null;
  id: string;
  last_error: string | null;
  params: Generated<Json>;
  selection: Json;
  started_at: Timestamp | null;
  status: Generated<string>;
  subject: string;
  succeeded: Generated<number>;
  tenant_id: string;
  total: number | null;
  updated_at: Generated<Timestamp>;
}

export interface OauthAccessTokens {
  agent_id: string | null;
  application: Generated<string>;
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  scope: string | null;
  subject: string;
  tenant_id: string;
  token_hash: string;
}

export interface OauthAuthorizationCodes {
  client_id: string;
  code: string;
  code_challenge: string | null;
  code_challenge_method: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  redirect_uri: string;
  scope: string | null;
  subject: string;
  tenant_id: string;
}

export interface OauthClients {
  client_id: string;
  client_name: string | null;
  client_secret_hash: string;
  created_at: Generated<Timestamp>;
  grant_types: Generated<string[]>;
  redirect_uris: string[];
  response_types: Generated<string[]>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OauthRefreshTokens {
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  scope: string | null;
  subject: string;
  tenant_id: string;
  token_hash: string;
  token_id: string;
}

export interface OidcRoleMappings {
  created_at: Generated<Timestamp>;
  id: string;
  idp_role: string;
  renkei_role: string;
  tenant_id: string;
}

export interface OperatorSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  issued_at: Timestamp;
  operator_name: string;
  session_id: string;
  subject: string;
  tenant_id: string;
}

export interface PendingOidcSignin {
  code_verifier: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  nonce: string;
  provider: string | null;
  scopes: string | null;
  state: string;
  subject: string | null;
  tenant_id: string;
}

export interface PlatformAuditLog {
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  details: Json | null;
  event_type: string;
  id: string;
  resource_id: string | null;
}

export interface PlatformSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface ProviderGrants {
  client_id: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  encrypted_access_token: string;
  encrypted_refresh_token: string;
  expires_at: Timestamp;
  granted_scopes: string[] | null;
  metadata: Generated<Json>;
  provider: string;
  provider_account_id: string;
  requested_scopes: Generated<string[]>;
  subject: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ProviderRefreshLocks {
  account_id: string;
  locked_at: Generated<Timestamp>;
  provider: string;
  tenant_id: string;
}

export interface PushSubscriptions {
  auth: string;
  created_at: Generated<Timestamp>;
  endpoint: string;
  id: string;
  p256dh: string;
  subject: string;
  tenant_id: string;
}

export interface SandboxFiles {
  batch_id: string | null;
  content_type: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  filename: string;
  id: string;
  size_bytes: number;
  source: string;
  storage_key: string;
  subject: string;
  tenant_id: string;
}

export interface ScheduleCalendars {
  created_at: Generated<Timestamp>;
  dates: Generated<Json>;
  id: string;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  last_used_at: Generated<Timestamp>;
  roles: Generated<string[]>;
  subject: string;
  tenant_id: string;
}

export interface TenantDomains {
  created_at: Generated<Timestamp>;
  domain: string;
  id: string;
  tenant_id: string;
}

export interface TenantJiraSites {
  claimed_at: Generated<Timestamp>;
  cloud_id: string;
  enabled: Generated<boolean>;
  jira_url: string;
  site_id: string;
  tenant_id: string;
}

export interface TenantOidc {
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  id: string;
  issuer: string;
  operator_idp_value: string | null;
  role_claim: string | null;
  tenant_id: string;
  user_idp_value: string | null;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: string;
  slug: string;
}

export interface TenantSettings {
  key: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface ToolCalls {
  agent_id: string | null;
  connector: string | null;
  duration_ms: number;
  ended_at: Timestamp;
  error_summary: string | null;
  id: string;
  started_at: Timestamp;
  status: string;
  subject: string | null;
  tenant_id: string;
  tool: string;
}

export interface UploadSlots {
  account_id: string;
  completed_at: Timestamp | null;
  content_type: string | null;
  created_at: Generated<Timestamp>;
  destination: Json;
  expires_at: Timestamp;
  filename: string;
  id: string;
  kind: string;
  max_bytes: number;
  result: string | null;
  status: Generated<string>;
  subject: string;
  tenant_id: string;
  token_hash: string;
}

export interface UserPreferences {
  key: string;
  subject: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface WebexDirtyWindows {
  day: string;
  marked_at: Generated<Timestamp>;
  room_id: string;
  subject: string | null;
  tenant_id: string;
}

export interface WebexSentMessages {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  message_id: string;
  tenant_id: string;
}

export interface WebhookSubscriptions {
  account_id: string;
  client_state: string;
  created_at: Generated<Timestamp>;
  delta_link: string | null;
  expires_at: Timestamp | null;
  id: string;
  last_run_items: Generated<number>;
  last_synced_at: Timestamp | null;
  provider: string;
  resource: string;
  subject: string | null;
  subscription_id: string | null;
  sync_status: Generated<string>;
  tenant_id: string;
  total_items: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  actionable_items: ActionableItems;
  agent_access_grants: AgentAccessGrants;
  agent_drafts: AgentDrafts;
  agent_jobs: AgentJobs;
  agent_jobs_dead_letters: AgentJobsDeadLetters;
  agent_memories: AgentMemories;
  agent_notifications: AgentNotifications;
  agent_optimizations: AgentOptimizations;
  agent_run_counters: AgentRunCounters;
  agent_run_log: AgentRunLog;
  agent_run_steps: AgentRunSteps;
  agent_runs: AgentRuns;
  agent_trigger_firings: AgentTriggerFirings;
  agent_triggers: AgentTriggers;
  agents: Agents;
  audit_events: AuditEvents;
  batch_job_items: BatchJobItems;
  batch_job_messages: BatchJobMessages;
  batch_job_messages_dead_letters: BatchJobMessagesDeadLetters;
  batch_job_schedules: BatchJobSchedules;
  batch_jobs: BatchJobs;
  connector_configs: ConnectorConfigs;
  content_watches: ContentWatches;
  email_classification_log: EmailClassificationLog;
  email_classifier_rules: EmailClassifierRules;
  email_cleaner_scripts: EmailCleanerScripts;
  email_extraction_templates: EmailExtractionTemplates;
  embedding_jobs: EmbeddingJobs;
  embedding_jobs_dead_letters: EmbeddingJobsDeadLetters;
  events: Events;
  events_dead_letters: EventsDeadLetters;
  file_share_connections: FileShareConnections;
  file_shares: FileShares;
  identities: Identities;
  jira_sessions: JiraSessions;
  knowledge_chunks: KnowledgeChunks;
  knowledge_reindex_runs: KnowledgeReindexRuns;
  llm_calls: LlmCalls;
  llm_model_configs: LlmModelConfigs;
  log_attr: LogAttr;
  log_attr_blob: LogAttrBlob;
  logs: Logs;
  mail_bulk_jobs: MailBulkJobs;
  oauth_access_tokens: OauthAccessTokens;
  oauth_authorization_codes: OauthAuthorizationCodes;
  oauth_clients: OauthClients;
  oauth_refresh_tokens: OauthRefreshTokens;
  oidc_role_mappings: OidcRoleMappings;
  operator_sessions: OperatorSessions;
  pending_oidc_signin: PendingOidcSignin;
  platform_audit_log: PlatformAuditLog;
  platform_settings: PlatformSettings;
  provider_grants: ProviderGrants;
  provider_refresh_locks: ProviderRefreshLocks;
  push_subscriptions: PushSubscriptions;
  sandbox_files: SandboxFiles;
  schedule_calendars: ScheduleCalendars;
  sessions: Sessions;
  tenant_domains: TenantDomains;
  tenant_jira_sites: TenantJiraSites;
  tenant_oidc: TenantOidc;
  tenant_settings: TenantSettings;
  tenants: Tenants;
  tool_calls: ToolCalls;
  upload_slots: UploadSlots;
  user_preferences: UserPreferences;
  webex_dirty_windows: WebexDirtyWindows;
  webex_sent_messages: WebexSentMessages;
  webhook_subscriptions: WebhookSubscriptions;
}
