/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ProviderRefreshLocks {
  account_id: string;
  locked_at: Generated<Timestamp>;
  provider: string;
  tenant_id: string;
}

export interface Identities {
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string;
  subject: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface JiraSessions {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  ip_address: string | null;
  last_used_at: Timestamp;
  tenant_id: string;
  user_agent: string | null;
}

export interface LogAttr {
  attr_id: Generated<Int8>;
  encrypted: Generated<boolean>;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  val: string | null;
  val_name: string;
  val_type: string;
}

export interface LogAttrBlob {
  attr_id: Generated<Int8>;
  encrypted: Generated<boolean>;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  val: Buffer;
  val_name: string;
}

export interface Logs {
  level: string;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  message: string;
}

export interface OauthAccessTokens {
  application: Generated<string>;
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  scope: string | null;
  subject: string;
  tenant_id: string;
  token_hash: string;
}

export interface OauthAuthorizationCodes {
  client_id: string;
  code: string;
  code_challenge: string | null;
  code_challenge_method: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  redirect_uri: string;
  scope: string | null;
  subject: string;
  tenant_id: string;
}

export interface OauthClients {
  client_id: string;
  client_name: string | null;
  client_secret_hash: string;
  created_at: Generated<Timestamp>;
  grant_types: Generated<string[]>;
  redirect_uris: string[];
  response_types: Generated<string[]>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OauthRefreshTokens {
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  scope: string | null;
  subject: string;
  tenant_id: string;
  token_hash: string;
  token_id: string;
}

export interface OidcRoleMappings {
  created_at: Generated<Timestamp>;
  id: string;
  idp_role: string;
  renkei_role: string;
  tenant_id: string;
}

export interface OperatorSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  issued_at: Timestamp;
  operator_name: string;
  session_id: string;
  subject: string;
  tenant_id: string;
}

export interface PendingOidcSignin {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  nonce: string;
  state: string;
  subject: string | null;
  tenant_id: string;
}

export interface PlatformAuditLog {
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  details: Json | null;
  event_type: string;
  id: string;
  resource_id: string | null;
}

export interface ProviderGrants {
  client_id: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  encrypted_access_token: string;
  encrypted_refresh_token: string;
  expires_at: Timestamp;
  metadata: Generated<Json>;
  provider: string;
  provider_account_id: string;
  scopes: Generated<string[]>;
  subject: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  last_used_at: Generated<Timestamp>;
  roles: Generated<string[]>;
  subject: string;
  tenant_id: string;
}

export interface TenantDomains {
  created_at: Generated<Timestamp>;
  domain: string;
  id: string;
  tenant_id: string;
}

export interface TenantJiraSites {
  claimed_at: Generated<Timestamp>;
  cloud_id: string;
  enabled: Generated<boolean>;
  jira_url: string;
  site_id: string;
  tenant_id: string;
}

export interface TenantOidc {
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  id: string;
  issuer: string;
  operator_idp_value: string | null;
  role_claim: string | null;
  tenant_id: string;
  user_idp_value: string | null;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: string;
  slug: string;
}

export interface Events {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  payload: Json;
  run_after: Generated<Timestamp>;
  source: string;
  status: Generated<string>;
  tenant_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface ActionableItems {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  evidence: Json;
  id: string;
  result: Json | null;
  source: string;
  status: Generated<string>;
  suggested_action: Json;
  summary: string;
  tenant_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ConnectorConfigs {
  connector: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  encrypted_secrets: string;
  settings: Generated<Json>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PlatformSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface TenantSettings {
  key: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface KnowledgeChunks {
  content: string;
  created_at: Generated<Timestamp>;
  /** pgvector value; written and compared via sql fragments, read as text. */
  embedding: string;
  id: string;
  metadata: Generated<Json>;
  provider: string;
  ref_id: string;
  tenant_id: string;
}

export interface DB {
  actionable_items: ActionableItems;
  connector_configs: ConnectorConfigs;
  events: Events;
  identities: Identities;
  knowledge_chunks: KnowledgeChunks;
  platform_settings: PlatformSettings;
  tenant_settings: TenantSettings;
  provider_refresh_locks: ProviderRefreshLocks;
  jira_sessions: JiraSessions;
  log_attr: LogAttr;
  log_attr_blob: LogAttrBlob;
  logs: Logs;
  oauth_access_tokens: OauthAccessTokens;
  oauth_authorization_codes: OauthAuthorizationCodes;
  oauth_clients: OauthClients;
  oauth_refresh_tokens: OauthRefreshTokens;
  oidc_role_mappings: OidcRoleMappings;
  operator_sessions: OperatorSessions;
  pending_oidc_signin: PendingOidcSignin;
  platform_audit_log: PlatformAuditLog;
  provider_grants: ProviderGrants;
  sessions: Sessions;
  tenant_domains: TenantDomains;
  tenant_jira_sites: TenantJiraSites;
  tenant_oidc: TenantOidc;
  tenants: Tenants;
}
