/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AtlassianGrants {
  account_id: string;
  atlassian_client_id: string;
  cloud_id: string;
  created_at: Generated<Timestamp>;
  encrypted_access_token: string;
  encrypted_refresh_token: string;
  expires_at: Timestamp;
  operator_name: string;
  scopes: Generated<string[]>;
  site_url: string;
  tenant_id: string;
}

export interface JiraSessions {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  ip_address: string | null;
  last_used_at: Timestamp;
  tenant_id: string;
  user_agent: string | null;
}

export interface LogAttr {
  attr_id: Generated<Int8>;
  encrypted: Generated<boolean>;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  val: string | null;
  val_name: string;
  val_type: string;
}

export interface LogAttrBlob {
  attr_id: Generated<Int8>;
  encrypted: Generated<boolean>;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  val: Buffer;
  val_name: string;
}

export interface Logs {
  level: string;
  log_id: Generated<Int8>;
  logged_timestamp: Timestamp;
  message: string;
}

export interface OidcRoleMappings {
  created_at: Generated<Timestamp>;
  id: string;
  idp_role: string;
  renkei_role: string;
  tenant_id: string;
}

export interface OperatorSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  issued_at: Timestamp;
  operator_name: string;
  session_id: string;
  subject: string;
  tenant_id: string;
}

export interface PendingOidcSignin {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  nonce: string;
  state: string;
  tenant_id: string;
}

export interface PlatformAuditLog {
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  details: Json | null;
  event_type: string;
  id: string;
  resource_id: string | null;
}

export interface TenantDomains {
  created_at: Generated<Timestamp>;
  domain: string;
  id: string;
  tenant_id: string;
}

export interface TenantJiraSites {
  claimed_at: Generated<Timestamp>;
  cloud_id: string;
  enabled: Generated<boolean>;
  jira_url: string;
  site_id: string;
  tenant_id: string;
}

export interface TenantOidc {
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  id: string;
  issuer: string;
  operator_idp_value: string | null;
  role_claim: string | null;
  tenant_id: string;
  user_idp_value: string | null;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: string;
  slug: string;
}

export interface DB {
  atlassian_grants: AtlassianGrants;
  jira_sessions: JiraSessions;
  log_attr: LogAttr;
  log_attr_blob: LogAttrBlob;
  logs: Logs;
  oidc_role_mappings: OidcRoleMappings;
  operator_sessions: OperatorSessions;
  pending_oidc_signin: PendingOidcSignin;
  platform_audit_log: PlatformAuditLog;
  tenant_domains: TenantDomains;
  tenant_jira_sites: TenantJiraSites;
  tenant_oidc: TenantOidc;
  tenants: Tenants;
}
