/**
 * Browser secrets — credentials an agent's browser may TYPE but the model
 * may never SEE. The pure half: how a secret is sealed, what a valid one
 * looks like, and the bounds every secret lives under. Storage and the
 * in-memory vault are apps/worker-sandbox's; the UI that supplies and
 * revokes them is apps/web's; both go through exactly this code.
 *
 * Why a passphrase, and why not the deployment key. Every other credential
 * Renkei holds is sealed under TOKEN_ENCRYPTION_KEY, which every process
 * that touches a grant can read. A browser secret is different in kind: it
 * is a person's login to some third-party site, handed over so an
 * autonomous agent can use it while they are not watching. So it gets its
 * own key, derived (scrypt) from a passphrase the person holds and Renkei
 * does not store — a database dump plus the deployment key yields nothing.
 * The passphrase is generated by Renkei (not chosen by the person — see
 * `generatePassphrase`) and shown exactly once; it exists in a Renkei
 * process only for the moments of sealing and unlocking, and the derived
 * key only in the sandbox worker's memory, until the unlock window closes
 * or the person locks or revokes the secret.
 *
 * The wire format is `sbx1.<salt>.<iv>.<tag>.<ciphertext>`, each part
 * base64 — deliberately its own prefix so a secret can never be mistaken
 * for a deployment-key envelope and decrypted with the wrong key.
 */

import { createCipheriv, createDecipheriv, randomBytes, randomInt, scryptSync } from 'node:crypto';
import { isBlockedIP } from './egress-guard';

export const SECRET_NAME_PATTERN = /^[a-z0-9][a-z0-9-]{0,63}$/;
export const SECRET_FIELD_PATTERN = /^[a-z0-9][a-z0-9_-]{0,31}$/;
export const SECRET_MAX_FIELDS = 8;
export const SECRET_VALUE_MAX_CHARS = 4096;
export const SECRET_MAX_HOSTS = 8;
/** Secrets one (tenantId, subject) may hold at once. */
export const SECRET_MAX_PER_SUBJECT = 50;
export const SECRET_PASSPHRASE_MIN_CHARS = 12;
export const SECRET_PASSPHRASE_MAX_CHARS = 256;

/** How long an unlock lasts unless the person says otherwise, and the most they may ask for. */
export const SECRET_UNLOCK_DEFAULT_MS = 8 * 60 * 60_000; // 8 hours
export const SECRET_UNLOCK_MAX_MS = 24 * 60 * 60_000; // 24 hours

/** How long a sealed secret is kept at all before the worker's sweep deletes it. */
export const SECRET_TTL_DEFAULT_MS = 30 * 24 * 60 * 60_000; // 30 days
export const SECRET_TTL_MAX_MS = 90 * 24 * 60 * 60_000; // 90 days

/** What a typed secret's value is replaced with wherever the model could read it. */
export const SECRET_MASK = '••••••';

const VERSION = 'sbx1';
const KEY_BYTES = 32;
const SALT_BYTES = 16;
const IV_BYTES = 12;
const TAG_BYTES = 16;
/** scrypt: 32MB, ~50–100ms per derivation — one per unlock, never per keystroke. */
const SCRYPT = { N: 1 << 15, r: 8, p: 1, maxmem: 64 * 1024 * 1024 };

/** One secret as every surface describes it — never a value, never the passphrase. */
export interface SandboxSecretSummary {
  id: string;
  name: string;
  fields: string[];
  hosts: string[];
  createdAt: Date;
  expiresAt: Date;
  lastUsedAt: Date | null;
  /** When the worker's in-memory key lapses; null when locked. */
  unlockedUntil: Date | null;
}

/** A reference a type step carries instead of text: which secret, which field. */
export interface SecretRef {
  name: string;
  field: string;
}

/**
 * A generated passphrase: five groups of five characters from an alphabet
 * without look-alikes (no 0/O, 1/l/I), ~124 bits. Generated rather than
 * chosen because a person's own passphrase is usually one they reuse; this
 * one is meant to be pasted into a password manager, not remembered.
 */
export function generatePassphrase(): string {
  const alphabet = 'abcdefghjkmnpqrstuvwxyz23456789';
  const groups: string[] = [];
  for (let group = 0; group < 5; group += 1) {
    let chunk = '';
    for (let index = 0; index < 5; index += 1) chunk += alphabet[randomInt(alphabet.length)];
    groups.push(chunk);
  }
  return groups.join('-');
}

export function deriveSecretKey(passphrase: string, salt: Buffer): Buffer {
  return scryptSync(Buffer.from(passphrase.normalize('NFKC'), 'utf8'), salt, KEY_BYTES, SCRYPT);
}

/** Seal a secret's fields under a fresh salt and the passphrase-derived key. */
export function sealSecretFields(fields: Record<string, string>, passphrase: string): string {
  const salt = randomBytes(SALT_BYTES);
  const key = deriveSecretKey(passphrase, salt);
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(JSON.stringify(fields), 'utf8'), cipher.final()]);
  return [
    VERSION,
    salt.toString('base64'),
    iv.toString('base64'),
    cipher.getAuthTag().toString('base64'),
    ciphertext.toString('base64'),
  ].join('.');
}

interface SealedParts {
  salt: Buffer;
  iv: Buffer;
  tag: Buffer;
  ciphertext: Buffer;
}

function parseSealed(sealed: string): SealedParts | null {
  const parts = sealed.split('.');
  if (parts.length !== 5 || parts[0] !== VERSION) return null;
  const [, saltPart, ivPart, tagPart, ciphertextPart] = parts;
  const salt = Buffer.from(saltPart, 'base64');
  const iv = Buffer.from(ivPart, 'base64');
  const tag = Buffer.from(tagPart, 'base64');
  if (
    salt.byteLength !== SALT_BYTES ||
    iv.byteLength !== IV_BYTES ||
    tag.byteLength !== TAG_BYTES
  ) {
    return null;
  }
  return { salt, iv, tag, ciphertext: Buffer.from(ciphertextPart, 'base64') };
}

/** The salt a sealed secret was derived with — what an unlock needs to derive the same key. */
export function sealedSalt(sealed: string): Buffer | null {
  return parseSealed(sealed)?.salt ?? null;
}

/** Open a sealed secret with an already-derived key; null on the wrong key or a tampered blob. */
export function openSecretFieldsWithKey(
  sealed: string,
  key: Buffer
): Record<string, string> | null {
  const parts = parseSealed(sealed);
  if (!parts) return null;
  try {
    const decipher = createDecipheriv('aes-256-gcm', key, parts.iv);
    decipher.setAuthTag(parts.tag);
    const plaintext = Buffer.concat([decipher.update(parts.ciphertext), decipher.final()]).toString(
      'utf8'
    );
    const parsed: unknown = JSON.parse(plaintext);
    const fields = validateSecretFields(parsed);
    return fields.ok ? fields.fields : null;
  } catch {
    return null;
  }
}

/** Open with the passphrase — the unlock path; null when the passphrase is wrong. */
export function openSecretFields(
  sealed: string,
  passphrase: string
): Record<string, string> | null {
  const salt = sealedSalt(sealed);
  if (!salt) return null;
  return openSecretFieldsWithKey(sealed, deriveSecretKey(passphrase, salt));
}

type Validated<T> = { ok: true } & T;
type Refused = { ok: false; message: string };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

export function validateSecretName(value: unknown): Validated<{ name: string }> | Refused {
  const name = typeof value === 'string' ? value.trim().toLowerCase() : '';
  if (!SECRET_NAME_PATTERN.test(name)) {
    return {
      ok: false,
      message: 'A secret name is 1-64 lowercase letters, digits and hyphens, e.g. vendor-portal.',
    };
  }
  return { ok: true, name };
}

/** 1-8 named string values, each a short identifier the model can refer to (username, password, ...). */
export function validateSecretFields(
  value: unknown
): Validated<{ fields: Record<string, string> }> | Refused {
  if (!isRecord(value)) return { ok: false, message: 'fields must be an object of name → value.' };
  const entries = Object.entries(value);
  if (entries.length === 0 || entries.length > SECRET_MAX_FIELDS) {
    return { ok: false, message: `A secret has 1-${SECRET_MAX_FIELDS} fields.` };
  }
  const fields: Record<string, string> = {};
  for (const [rawName, rawValue] of entries) {
    const name = rawName.trim().toLowerCase();
    if (!SECRET_FIELD_PATTERN.test(name)) {
      return {
        ok: false,
        message: `Field name "${rawName}" — use 1-32 lowercase letters, digits, hyphens or underscores.`,
      };
    }
    if (typeof rawValue !== 'string' || rawValue.length === 0) {
      return { ok: false, message: `Field "${name}" needs a value.` };
    }
    if (rawValue.length > SECRET_VALUE_MAX_CHARS) {
      return {
        ok: false,
        message: `Field "${name}" is longer than ${SECRET_VALUE_MAX_CHARS} characters.`,
      };
    }
    if (name in fields) return { ok: false, message: `Field "${name}" is listed twice.` };
    fields[name] = rawValue;
  }
  return { ok: true, fields };
}

const HOST_PATTERN = /^(\*\.)?[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;

/** One host entry, leniently read (a pasted URL loses its scheme and path) and strictly checked. */
function normalizeHost(raw: string): string | null {
  let host = raw.trim().toLowerCase();
  if (host.includes('://')) {
    try {
      host = new URL(host).hostname;
    } catch {
      return null;
    }
  }
  host = host.replace(/\/.*$/, '').replace(/:\d+$/, '');
  if (!HOST_PATTERN.test(host)) return null;
  if (isBlockedIP(host.replace(/^\*\./, ''))) return null;
  return host;
}

/**
 * 1-8 hostnames a secret may be typed into: exact (`portal.vendor.com`) or
 * a wildcard for subdomains (`*.vendor.com`). Required, and deliberately
 * not optional: a credential with no host scope could be typed into any
 * page a task wandered onto.
 */
export function validateSecretHosts(value: unknown): Validated<{ hosts: string[] }> | Refused {
  const raw = Array.isArray(value) ? value : typeof value === 'string' ? value.split(/[\s,]+/) : [];
  const hosts: string[] = [];
  for (const entry of raw) {
    if (typeof entry !== 'string' || !entry.trim()) continue;
    const host = normalizeHost(entry);
    if (!host) {
      return {
        ok: false,
        message: `"${entry.trim()}" is not a usable hostname — e.g. portal.vendor.com or *.vendor.com.`,
      };
    }
    if (!hosts.includes(host)) hosts.push(host);
  }
  if (hosts.length === 0) {
    return { ok: false, message: 'Name at least one hostname this secret may be typed into.' };
  }
  if (hosts.length > SECRET_MAX_HOSTS) {
    return { ok: false, message: `At most ${SECRET_MAX_HOSTS} hostnames per secret.` };
  }
  return { ok: true, hosts };
}

/** Whether a page's host is one the secret is scoped to. `*.x.com` covers subdomains, not x.com itself. */
export function secretHostAllowed(pageHost: string, hosts: readonly string[]): boolean {
  const host = pageHost.trim().toLowerCase();
  if (!host) return false;
  return hosts.some((allowed) =>
    allowed.startsWith('*.')
      ? host.endsWith(allowed.slice(1)) && host !== allowed.slice(2)
      : host === allowed
  );
}

export function validatePassphrase(value: unknown): Validated<{ passphrase: string }> | Refused {
  if (typeof value !== 'string') return { ok: false, message: 'A passphrase is required.' };
  if (value.length < SECRET_PASSPHRASE_MIN_CHARS) {
    return {
      ok: false,
      message: `A passphrase is at least ${SECRET_PASSPHRASE_MIN_CHARS} characters.`,
    };
  }
  if (value.length > SECRET_PASSPHRASE_MAX_CHARS) {
    return {
      ok: false,
      message: `A passphrase is at most ${SECRET_PASSPHRASE_MAX_CHARS} characters.`,
    };
  }
  return { ok: true, passphrase: value };
}

/** `{ name, field }` as a type step carries it, or null when malformed. */
export function parseSecretRef(value: unknown): SecretRef | null {
  if (!isRecord(value)) return null;
  const name = validateSecretName(value.name);
  const field = typeof value.field === 'string' ? value.field.trim().toLowerCase() : '';
  if (!name.ok || !SECRET_FIELD_PATTERN.test(field)) return null;
  return { name: name.name, field };
}

function clampMs(value: unknown, fallback: number, max: number): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) return fallback;
  return Math.min(Math.floor(value), max);
}

/** An unlock window from the wire — the default when absent, never past the ceiling. */
export function unlockWindowMs(value: unknown): number {
  return clampMs(value, SECRET_UNLOCK_DEFAULT_MS, SECRET_UNLOCK_MAX_MS);
}

/** A secret's lifetime from the wire — the default when absent, never past the ceiling. */
export function secretTtlMs(value: unknown): number {
  return clampMs(value, SECRET_TTL_DEFAULT_MS, SECRET_TTL_MAX_MS);
}

/**
 * Blank out every secret value in text bound for the model — a snapshot,
 * a URL, an error message. Belt and braces over the in-page masking: a
 * site that echoes a username back in its own text, or a form that put a
 * value into the query string, must not become the channel that reveals
 * it. Values shorter than four characters are left alone: masking every
 * "1" in a page would destroy it, and such a value was never secret.
 */
export function scrubSecretValues(text: string, values: Iterable<string>): string {
  let scrubbed = text;
  for (const value of values) {
    if (value.length < 4) continue;
    // The value as typed, as a URL component, and as a form field — a GET
    // form encodes "!" as %21 and spaces as "+", which encodeURIComponent
    // does not, and the query string is exactly where a submitted secret
    // would otherwise show up.
    const spellings = new Set([
      value,
      encodeURIComponent(value),
      new URLSearchParams({ v: value }).toString().slice(2),
    ]);
    for (const spelling of spellings) {
      if (spelling.length >= 4) scrubbed = scrubbed.split(spelling).join(SECRET_MASK);
    }
  }
  return scrubbed;
}
