/**
 * Bundles the preview-card sources into inline HTML string constants.
 *
 * Each widget becomes one self-contained HTML document (MCP Apps forbids
 * external assets — the host's CSP blocks anything we did not inline) and is
 * emitted as a generated TypeScript module the server imports. The generated
 * files are checked in so `next build` needs no extra step; re-run this after
 * editing anything under src/:
 *
 *   node lib/mcp-widgets/build.mjs   (from apps/web)
 */

import { buildSync } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

const WIDGETS = [
  { entry: 'email-compose.ts', exportName: 'EMAIL_COMPOSE_HTML', title: 'Email preview' },
  { entry: 'chat-message.ts', exportName: 'CHAT_MESSAGE_HTML', title: 'Message preview' },
  { entry: 'meeting-preview.ts', exportName: 'MEETING_PREVIEW_HTML', title: 'Meeting preview' },
  { entry: 'issue-preview.ts', exportName: 'ISSUE_PREVIEW_HTML', title: 'Work item preview' },
  { entry: 'results-list.ts', exportName: 'RESULTS_LIST_HTML', title: 'Results' },
];

mkdirSync(join(here, 'generated'), { recursive: true });

for (const widget of WIDGETS) {
  const result = buildSync({
    entryPoints: [join(here, 'src', widget.entry)],
    bundle: true,
    minify: true,
    format: 'iife',
    target: 'es2020',
    write: false,
  });
  for (const warning of result.warnings) console.warn(warning.text);
  const js = result.outputFiles[0].text;

  const html =
    '<!doctype html><html><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width, initial-scale=1">' +
    `<title>${widget.title}</title></head><body><div id="root"></div>` +
    // </script> inside the bundle would end the tag early; split the token.
    `<script>${js.replace(/<\/script/gi, '<\\/script')}</script></body></html>`;

  const moduleName = widget.entry.replace(/\.ts$/, '');
  // Hosts cache ui:// templates by URI, and a stale template rendering a
  // newer data contract fails silently ("No results." on a card full of
  // data). Embedding a content hash in the URI makes every template change
  // a NEW resource the host has never cached — template and contract move
  // in lockstep by construction.
  const hash = createHash('sha256').update(html).digest('hex').slice(0, 10);
  const out =
    `// GENERATED by lib/mcp-widgets/build.mjs from src/${widget.entry} — do not edit.\n` +
    `export const ${widget.exportName}: string = ${JSON.stringify(html)};\n` +
    `export const ${widget.exportName.replace(/_HTML$/, '_HASH')}: string = ${JSON.stringify(hash)};\n`;
  writeFileSync(join(here, 'generated', `${moduleName}.ts`), out);
  console.log(`${moduleName}: ${(html.length / 1024).toFixed(1)} KiB (${hash})`);
}
